#!/bin/sh

cd piston-api
msg="$(git log -1 --pretty=%B)"
cd ../

# echo $PWD

# unset GIT_DIR
# unset GIT_WORK_TREE
# git config --get remote.origin.url

# echo "UNSET GIT DIR"
git status

# echo "RESET STAGE"
git reset

# echo "ADD PISTON API"
git add piston-api

# echo "COMMIT"
git commit -m "Piston: $msg"
