#!/bin/sh

cd protocol
msg="$(git log -1 --pretty=%B)"
cd ../

# echo $PWD

# unset GIT_DIR
# unset GIT_WORK_TREE
# git config --get remote.origin.url

# echo "UNSET GIT DIR"
# git status

# echo "RESET STAGE"
git reset

# echo "ADD PROTOCOL"
git add protocol-translator

# echo "COMMIT"
git commit -m "Translator: $msg"
